USE zzz;

CREATE TABLE IF NOT EXISTS boss_info (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  boss_name VARCHAR(255) NOT NULL COMMENT 'Boss名称',
  defense INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '防御力',
  level INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '等级',
  boss_image VARCHAR(500) DEFAULT NULL COMMENT 'Boss图片',
  weakness VARCHAR(255) DEFAULT NULL COMMENT '弱点',
  resistance VARCHAR(255) DEFAULT NULL COMMENT '抗性',
  PRIMARY KEY (id),
  UNIQUE KEY uk_boss_name (boss_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Boss基础信息表';
