USE zzz;

CREATE TABLE IF NOT EXISTS id_buff (
  id INT UNSIGNED NOT NULL COMMENT 'Buff ID（如14101=1.4第1期Buff1）',
  version VARCHAR(50) NOT NULL COMMENT '版本',
  phase VARCHAR(50) NOT NULL COMMENT '期数',
  buff_image VARCHAR(500) DEFAULT NULL COMMENT 'Buff图片',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Buff ID信息表';
