USE zzz;

CREATE TABLE IF NOT EXISTS id_table (
  id INT UNSIGNED NOT NULL COMMENT '版本期数ID（如1.4第1期为141）',
  tid INT UNSIGNED NOT NULL COMMENT '游戏内ID（如69001）',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='期数ID映射表';
